name: backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntsu-latast
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm run ci
      - run: npm run test
      - run: npm run build